# -*- coding: utf-8 -*-
"""Disease Detection CNN.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MEZM2gaZAVTdQEtHPzD7dhATvCqql9VH
"""

import tensorflow as tf
print("TensorFlow version:", tf.__version__)
import pickle

import warnings
warnings.filterwarnings('ignore')

# !pip install -qqq numpy pandas matplotlib seaborn scikit-learn streamlit librosa

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import sklearn
import streamlit as st
import librosa

device_name = tf.test.gpu_device_name()
if device_name != '/device:GPU:0':
  print('GPU device not found')
else:
  print('Found GPU at: {}'.format(device_name))

training_set = tf.keras.utils.image_dataset_from_directory(
    '/content/PlantVillage/train',
    labels="inferred",
    label_mode="categorical",
    class_names=None,
    color_mode="rgb",
    batch_size=32,
    image_size=(128, 128),
    shuffle=True,
    seed=None,
    validation_split=None,
    subset=None,
    interpolation="bilinear",
    follow_links=False,
    crop_to_aspect_ratio=False,
)

validation_set = tf.keras.utils.image_dataset_from_directory(
    '/content/PlantVillage/val',
    labels="inferred",
    label_mode="categorical",
    class_names=None,
    color_mode="rgb",
    batch_size=32,
    image_size=(128, 128),
    shuffle=True,
    seed=None,
    validation_split=None,
    subset=None,
    interpolation="bilinear",
    follow_links=False,
    crop_to_aspect_ratio=False,
)

for images, labels in training_set.take(1):
    print(images.dtype)
    print(images.numpy().min())
    print(images.numpy().max())

## Model Training

# !unzip /content/archive.zip -d /content/

from tensorflow.keras.layers import Dense,Conv2D,MaxPool2D,Flatten,Dropout
from tensorflow.keras.models import Sequential

model = Sequential()

# Block 1
model.add(Conv2D(32, 3, padding='same', activation='relu', input_shape=(128,128,3)))
model.add(Conv2D(32, 3, activation='relu'))
model.add(MaxPool2D(pool_size=2, strides=2))

# Block 2
model.add(Conv2D(64, 3, padding='same', activation='relu'))
model.add(Conv2D(64, 3, activation='relu'))
model.add(MaxPool2D(pool_size=2, strides=2))

# Block 3
model.add(Conv2D(128, 3, padding='same', activation='relu'))
model.add(Conv2D(128, 3, activation='relu'))
model.add(MaxPool2D(pool_size=2, strides=2))

# Block 4
model.add(Conv2D(256, 3, padding='same', activation='relu'))
model.add(Conv2D(256, 3, activation='relu'))
model.add(MaxPool2D(pool_size=2, strides=2))

# Block 5
model.add(Conv2D(512, 3, padding='same', activation='relu'))
model.add(Conv2D(512, 3, activation='relu'))
model.add(MaxPool2D(pool_size=2, strides=2))

model.add(Dropout(0.25))          # light dropout before dense head
model.add(Flatten())
model.add(Dense(1500, activation='relu'))
model.add(Dropout(0.4))
model.add(Dense(38, activation='softmax'))

model.compile(optimizer='adam' , loss='categorical_crossentropy',metrics=['accuracy'])

model.summary()

from tensorflow.keras.callbacks import EarlyStopping

early_stop = EarlyStopping(
    monitor='val_loss',
    patience=5,
    restore_best_weights=True
)

training_history = model.fit(x=training_set,validation_data=validation_set,epochs=10 , callbacks=[early_stop])

plt.plot(training_history.history['accuracy'])
plt.plot(training_history.history['val_accuracy'])

plt.xlabel("Epoch")
plt.ylabel("Accuracy")
plt.legend(["Training", "Validation"])

plt.show()

"""Accuracy"""

train_loss,train_acc = model.evaluate(training_set)

print(train_loss,train_acc)

val_loss,val_acc = model.evaluate(validation_set)

print(val_loss,val_acc)

from sklearn.metrics import classification_report, confusion_matrix
import numpy as np

validation_set = tf.keras.utils.image_dataset_from_directory(
    '/content/PlantVillage/val',
    labels="inferred",
    label_mode="categorical",
    batch_size=32,
    image_size=(128,128),
    shuffle=False
)

import numpy as np

y_true = np.concatenate([labels.numpy() for images, labels in validation_set])

# Convert one-hot → class index
y_true = np.argmax(y_true, axis=1)

y_true = []

for images, labels in validation_set:
    y_true.extend(np.argmax(labels.numpy(), axis=1))

y_true = np.array(y_true)

y_pred_prob = model.predict(validation_set)

y_pred = np.argmax(y_pred_prob, axis=1)

class_names = validation_set.class_names

print(class_names)

cm = confusion_matrix(y_true, y_pred)
print(cm)

from sklearn.metrics import classification_report

print(classification_report(
    y_true,
    y_pred,
    target_names=class_names
))

import matplotlib.pyplot as plt
import seaborn as sns

plt.figure(figsize=(15,15))
sns.heatmap(cm,
            annot=True,
            fmt='d',
            cmap='Blues',
            xticklabels=class_names,
            yticklabels=class_names)

plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.title("Confusion Matrix")
plt.show()

"""Save Model"""

model.save("trained_model.keras")

# Load the saved Keras model
loaded_model = tf.keras.models.load_model('trained_model.keras')

# Save the loaded model as a pickle file
with open('trained_model.pkl', 'wb') as file:
    pickle.dump(loaded_model, file)

print("Model saved as trained_model.pkl")

training_history.history

#Recording History in json
import json
with open("training_hist.json","w") as f:
    json.dump(training_history.history,f)

"""Download Model"""

from google.colab import files

files.download('trained_model.keras')
files.download('training_hist.json')

"""download pickle file"""

from google.colab import files

files.download('trained_model.pkl')

"""Model Test"""

