export const STORY_CHAPTERS = [
  { id: 'crop', number: '01', eyebrow: 'RECOGNISE THE CROP', heading: 'Start with what is growing.', copy: 'Radar and optical observations build a seasonal view of the field. CropSense first classifies Paddy or Non-Paddy, because rice-specific analysis should only continue when the crop result supports it.', qualification: 'Satellite classification is evidence about the field—not a substitute for a field record.', tags: ['Sentinel-1', 'Sentinel-2', 'Paddy / Non-Paddy'] },
  { id: 'growth', number: '02', eyebrow: 'FOLLOW THE SEASON', heading: 'Growth changes the meaning of every signal.', copy: 'The same observation can mean something different after transplanting, during vegetative growth, or near maturity. CropSense estimates growth stage to place later evidence in the crop cycle.', qualification: 'Growth-stage estimation is provisional and should be checked against known planting dates.', tags: ['Crop cycle', 'Stage context', 'Provisional'] },
  { id: 'stress', number: '03', eyebrow: 'NOTICE THE CHANGE', heading: 'Find signals that deserve a closer look.', copy: 'Persistent optical and radar anomalies can raise moisture-stress risk. CropSense separates a single unusual observation from a pattern that is corroborated over time.', qualification: 'Stress is supporting evidence. It never becomes millimetres of deficit or sets irrigation quantity.', tags: ['Persistence', 'Corroboration', 'Field inspection'] },
  { id: 'weather', number: '04', eyebrow: 'READ THE ATMOSPHERE', heading: 'See what arrives—and what leaves.', copy: 'Historical rainfall, atmospheric demand, and the forecast provide the weather context around the field. Together they explain incoming water and expected crop water use.', qualification: 'Satellite rainfall and reanalysis are coarse estimates, not a rain gauge inside the field.', tags: ['Rainfall', 'ET₀', 'Five-day forecast'] },
  { id: 'balance', number: '05', eyebrow: 'ACCOUNT FOR WATER', heading: 'Follow every millimetre through the field.', copy: 'The paddy water balance combines rainfall, recorded irrigation, crop use, ponded water, soil depletion, seepage, and overflow to estimate the current water deficit.', qualification: 'Missing irrigation is shown as unrecorded, and assumptions remain visible in the evidence level.', tags: ['Ponding', 'Root zone', 'Deficit in mm'] },
  { id: 'irrigation', number: '06', eyebrow: 'PLAN THE NEXT STEP', heading: 'Turn the balance into a measured action.', copy: 'Rule-based advice combines the current and projected balance with forecast rain, field area, and application efficiency to recommend timing, depth, and approximate volume.', qualification: 'Forecast rain is credited conservatively. Advice remains provisional decision support.', tags: ['Timing', 'Water depth', 'Field volume'] },
  { id: 'evidence', number: '07', eyebrow: 'SEE THE REASON', heading: 'Understand why the system reached its advice.', copy: 'Saved observations, charts, assumptions, warnings, and evidence levels keep each conclusion inspectable. An optional AI explanation can describe these results in plain language.', qualification: 'AI explains available evidence; it does not calculate or override irrigation quantity.', tags: ['Provenance', 'Warnings', 'Evidence level'] },
  { id: 'field', number: '08', eyebrow: 'YOUR FIELD', heading: 'Now bring your own field into view.', copy: 'The complete landscape is the context. Your polygon is where CropSense begins: validating the field, retrieving observations, and preserving the evidence behind each result.', qualification: 'This landscape is illustrative. Real field selection opens the operational field tool.', tags: ['Field polygon', 'Coverage checks', 'Analysis history'] },
];

export const STORY_COUNT = STORY_CHAPTERS.length;
